### ISSUE TITLE
ERROR in CORE

### ISSUE THREAD

**Issue by AndreasFromDanmark** [ExterCore/exter_core#2]
![image](https://github.com/user-attachments/assets/cc7633cf-54ed-4a34-9c79-5bfa893663e1)

Line 488
![image](https://github.com/user-attachments/assets/fc4aefdd-ba48-4bb7-bab4-2b920a1e85ba)

**Comment by sobing4413** [comment]
sorry for my negligence. there is a small error in our github API. we have fixed it. have a nice day 😊
